# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
#
# ,--------.      ,--.   ,--. ,--.
# '--.  .--',---.  \  `.'  /,-'  '-.
#    |  |  | .-. :  .'    \ '-.  .-'
#    |  |  \   --. /  .'.  \  |  |
#    `--'   `----''--'   '--' `--'




## => Site Settings
##############################
text_skin : dark # default
highlight_theme : ocean 
url     : https://sunzhongmeng.github.io 
baseurl : /
title   : Sunzhongmeng's blog
description: > 
  个人小站


## => Language and Timezone
##############################
lang: zh 
timezone:  Asia/Shanghai 


## => Author and Social
##############################
author:
  name      : sunzhongmeng
  email     : sunzhongmeng@gmail.com
  facebook  : sunzhongmeng
  twitter   : sunzhongmeng
  
  github    : sunzhongmeng # "user_name" the last part of your profile url, e.g. https://github.com/user_name
## => GitHub Repository (if the site is hosted by GitHub)
##############################
repository: sunzhongmeng/sunzhongmeng.github.io
repository_tree: master


## => Paths
##############################
paths:
  root    : /
  home    : /
  archive : /archive.html
  rss     : /feed.xml


## => Post
##############################
## excerpt
excerpt_separator: <!--more-->

## license
license: CC-BY-NC-4.0 

## TOC
toc:
  selectors: # "h1,h2,h3" (default)


## => Markdown Enhancements
##############################
## Mathjax
mathjax: # false (default), true
mathjax_autoNumber: # false (default), true

## Mermaid
mermaid: # false (default), true

## Chart
chart: # false (default), true


## => Paginate
##############################
paginate: 8
paginate_path: /page:num 


## => Sources
##############################
sources: # bootcdn (default), unpkg


## => Comments
##############################
comments:
  provider: gitalk 
  gitalk:
    clientID    : 43574655dc9f632cbd6c # GitHub Application Client ID
    clientSecret: 8e84f7dc1967dcf457de496aa6c6bb7f4fc9b199 # GitHub Application Client Secret
    repository  : sunzhongmeng.github.io # GitHub repo
    owner       : sunzhongmeng # GitHub repo owner
    admin: sunzhongmeng 


## => Pageview
##############################
pageview:
  provider: leancloud 

  ## Leancloud
  leancloud:
    app_id    : f66aG3WOmShf6ooBBGso9LIs-gzGzoHsz # LeanCloud App id
    app_key   : wU38pcnTC3JqtkeoES7QmLyd # LeanCloud App key
    app_class : Counter # LeanCloud App class


## => Analytics
##############################
analytics:
  provider: google 

  ## Google Analytics
  google:
    tracking_id : 


## => Build
##############################
markdown    : kramdown
highlighter : rouge
permalink   : date

exclude:
  - CHANGELOG.md
  - HOW_TO_RELEASE.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README-*.md
  - README.md
  - gulpfile.js
  - jekyll-text-theme.gemspec
  - package-lock.json
  - package.json
  - /docs
  - /node_modules
  - /screenshots
  - /test
  - /vendor

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: article
      sharing: true
      license: true
      aside:
        toc: true
      show_edit_on_github: true
      pageview: true


## => Plugins
##############################
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
